### PR TITLE
warning fixes

### PR DESCRIPTION
**Pull request by krojew**

### CODE REVIEW

**Comment by bonifaido** [comment]
Sorry, I have to fix the Travis config, I guess the Java version has changed here.

**Comment by krojew** [comment]
@bonifaido it would be a good idea to not explicitly use java for testing, but rather the official ZK docker image.

**Comment by bonifaido** [comment]
The Java-based class represents a multi-node cluster, which covers more code paths (reconnection to next server for example). If this can be achieved with the Docker version I'm happy to change it.

**Comment by bonifaido** [comment]
I'm fixing the test for now in https://github.com/bonifaido/rust-zookeeper/pull/61

**Comment by krojew** [comment]
@bonifaido docker based approach gives you the possibility to do whatever you wish, just as with the native approach. You simply don't need to depend on anything other installed than docker.

**Pull request merged**
