### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jwilm**
This updates dependencies mio, byteorder, and bytes and replaces the RingBuf usage with a BytesMut implementation (to fix a bug).

### CODE REVIEW

**Comment by bonifaido** [comment]
Look very good, thank you for your contribution!

**Comment by bonifaido** [comment]
Would you like to have a new release version bump?

**Comment by jwilm** [comment]
@bonifaido that would certainly be appreciated. :smile:

**Comment by bonifaido** [comment]
Just release 0.5.0, sorry for the delay! https://crates.io/crates/zookeeper

**Pull request merged**
