### PR TITLE
Fixes issue/37 - zookeeper cannot build on release

### PR DESCRIPTION
**Pull request by fulmicoton**

### CODE REVIEW

**Comment by fulmicoton** [comment]
This is a suggestion on how to address the issue. It actually breaks public API.

**Comment by tgockel** [comment]
Breaking the public API is okay since we're still in 0.x 😄

**Comment by tgockel** [comment]
I'm going to pull this into my 0.4 line so we respect semantic versioning.

**Comment by bonifaido** [comment]
Thank you very much for the fix @fulmicoton!
I'm happy to merge this, but I just realised that the integration test broke, because Maven has disappeared from the Travis build which is required to build the ZooKeeper test suite.
I will push a fix into master for this, could you please rebase this branch on it?

**Comment by fulmicoton** [comment]
just rebase... Not sure why but apparently it closes the PR. Starting a new one.

**Pull request closed without merging**
